### ISSUE TITLE
Formula evaluation doesn't work

### ISSUE THREAD

**Issue by 229c9cf0** [tgrosinger/md-advanced-tables#42] opened 2022-01-19 23:29 UTC
Just installed Advanced Tables 0.17.0 with Obsidian 0.13.19 (live preview enabled) on Windows.

Sample tables with formulas (copied from #27, #32 which should be correct and work) don't evaluate formulas.

I tried triggering evaluation from both the toolbar as well as the command palette, no effect. Console also shows no warnings, errors, or anything at all in response to either. Same behavior in a fresh vault with no other plugins installed.

No clue what else to add, can you reproduce the behavior based on just this?

**Comment by tgrosinger** [comment] 2022-01-20 03:55
I think this was probably caused by https://github.com/tgrosinger/advanced-tables-obsidian/issues/162. Please give it another try on 0.17.2.

**Comment by tgrosinger** [comment] 2022-01-20 04:57
I'm going to close this issue, but please reopen if the issue is still occuring.

**Closed by tgrosinger** 2022-01-20 04:57 UTC

**Comment by 229c9cf0** [comment] 2022-01-20 13:06
Confirmed fixed, thanks for the quick response!

**Comment by airtonix** [comment] 2022-10-18 09:34
broken again

**Comment by 0xcrypto** [comment] 2022-12-01 14:01
```md
| Expense                | Due On         | Amount | Minimum Due |
| ---------------------- | -------------- | ------ | ----------- |
| Credit Card Bill       | [[2022-12-03]] | 17249  | 5000        |
| Some Paid Expense      |                | 6345   | 0           |
| **Total**              |                |        |             |
<!-- TBLFM: @>$3=sum(@I..@-1) -->
```

Am I doing something wrong or is it because of this issue?

**Comment by prime-optimal** [comment] 2023-01-11 14:56
> ```lisp
> | Expense                | Due On         | Amount | Minimum Due |
> | ---------------------- | -------------- | ------ | ----------- |
> | Credit Card Bill       | [[2022-12-03]] | 17249  | 5000        |
> | Some Paid Expense      |                | 6345   | 0           |
> | **Total**              |                |        |             |
> 
> ```
> 
> Am I doing something wrong or is it not working because of this issue?

Same here, I just copied and pasted the example formula and it doesn't work
