### ISSUE TITLE
Support formulas for hours:minutes syntax

### ISSUE THREAD

**Issue by tim-hilt** [tgrosinger/md-advanced-tables#59] opened 2022-11-28 08:22 UTC
**Is your feature request related to a problem? Please describe.**

Not related to a problem. I mainly use tables in Obsidian to keep track of my working hours. My table has the following example-format:

```
| Ticket   | Description          | Time |
| -------- | -------------------- | ---- |
| JIRA-123 | Do something awesome | 1:15 |
```

I tried to use the sum-function, however it seems to only take the first integer `1` into account.

**Describe the solution you'd like**

I'd like support for hours:minutes syntax for the table formulas

**Describe alternatives you've considered**

- Separate columns for hours and minutes, however this is more stuff to type
- Only writing minutes, but then I might have to calculate the minutes in my head

**Additional context**

- Is there maybe already a way to do this?
- I might consider submitting a PR if you see supporting this format as beneficial. Could you point me to the location in the code?

**Comment by tgrosinger** [comment] 2023-05-25 15:19
I think this is a duplicate of #31

**Closed by tgrosinger** 2023-05-25 15:19 UTC
Labels: enhancement
