### ISSUE TITLE
Formulas don't output result

### ISSUE THREAD

**Issue by belen-albeza** [tgrosinger/md-advanced-tables#27] opened 2021-07-28 19:08 UTC
Hi, I'm having trouble getting formulas to work. Table editing functionality (auto formatting, etc.) works fine, but when I comes to formula I don't see any output at all in the regular view. For instance, typing this example from the documentation:

```md
| Item              | Grams |
| ----------------- | ----- |
| Whole Wheat Flour | 110   |
| Bread Flour       | 748   |
| Warm Water        | 691   |
| Salt              | 18    |
| Starter           | 40    |
| **Total Grams**   |       |
<!-- TBLFM: @>$2=sum(@I..@-1) -->
```

Renders this:

<img width="285" alt="Screenshot 2021-07-28 at 21 07 04" src="https://user-images.githubusercontent.com/63681/127381528-392b1968-e7b0-45c5-a4ef-a0edfdc328b8.png">

I'm sure I must be doing something wrong, but I've looked at the settings and it seems that besides enabling the plugin there's nothing else for me to do to enable formulas.

Thanks for the help!

**Comment by khorton** [comment] 2021-07-28 19:25
The formula won't be evaluated until tell Advanced Tables to evaluate them.  Either select the command in the Advanced Tables part of the Command Palette, or the following:

1. Enable the Advanced Tables toolbar icon (preferences, "Show icon in sidebar" item)
2. open the Advanced Tables toolbar by clicking on the Advanced Tables icon in the sidebar
3. place the cursor inside the table
4. click on the "fx" icon in the Advanced Tables toolbar

**Comment by belen-albeza** [comment] 2021-07-29 09:57
Hey, thanks for answering so quickly. I got it working with running the `Evaluate table formulas` command, but clicking on the "fx" button in the sidebar panel does nothing (the cursor being in the same place as when executing the command). When opening the developer tools, I can see this error in the console:

```
obsidian-text-editor.ts:18 Uncaught TypeError: Cannot read property 'getCursor' of undefined
    at ObsidianTextEditor.getCursorPosition (eval at <anonymous> (app.js:1), <anonymous>:23195:41)
    at TableEditor.cursorIsInTable (eval at <anonymous> (app.js:1), <anonymous>:22331:38)
    at TableEditor.cursorIsInTable (eval at <anonymous> (app.js:1), <anonymous>:23258:30)
    at TableControlsView._this.withTE (eval at <anonymous> (app.js:1), <anonymous>:23446:21)
    at HTMLDivElement.eval (eval at <anonymous> (app.js:1), <anonymous>:23440:60)
```

Thanks

**Comment by Write** [comment] 2021-07-31 23:18
I Got the same error when trying the example formulas.

![image](https://user-images.githubusercontent.com/541722/127754479-a2f43f28-d4f7-4309-84ce-8b155f65aa0d.png)

(I put my anywhere in the table)

![image](https://user-images.githubusercontent.com/541722/127754489-c9702f09-a53f-48db-99cf-33a5a7fa2bc4.png)

**Comment by ramisedhom** [comment] 2021-09-08 11:58
I got same exact behavior and error

**Comment by pynem** [comment] 2021-09-24 09:51
I see the same thing. The closing comment marker has been changed from `-->` to an arrow, which apparently is [not a bug](https://forum.obsidian.md/t/closing-comment-renders-as-arrow/12663).

**Comment by tgrosinger** [comment] 2021-11-26 00:38
This was a bug in the Obsidian plugin that should be resolved with the next release.
See https://github.com/tgrosinger/advanced-tables-obsidian/issues/105

**Closed by tgrosinger** 2021-11-26 00:38 UTC
